from distutils.core import setup

from setuptools import find_packages

setup(
    name='dj-dna-streaming-python',
    version='1.0.1',
    description='Dow Jones DNA Streaming Project',
    author='Chris Flesche',
    author_email='chris.flesche@dowjones.com',
    url='https://github.dowjones.net/syndicationhub/dj-dna-streaming-python/',
    packages=find_packages(exclude='tests'),

    # metadata for upload to PyPI
    license="PSF",

    include_package_data=True,

    install_requires=[
        "backports-abc==0.5",
        "BigQuery-Python==1.10.0",
        "boto==2.39.0",
        "certifi==2016.9.26",
        "configparser==3.5.0",
        "coverage==4.3.4",
        "docutils==0.13.1",
        "dominate==2.3.1",
        "enum34==1.1.6",
        "flake8==3.3.0",
        "Flask==0.10.1",
        "Flask-Bootstrap==3.3.5.7",
        "Flask-Cors==2.1.2",
        "Flask-SQLAlchemy==2.1",
        "funcsigs==1.0.2",
        "future==0.16.0",
        "futures==3.0.5",
        "gapic-google-cloud-datastore-v1==0.14.1",
        "gapic-google-cloud-logging-v2==0.90.1",
        "gapic-google-pubsub-v1==0.10.1",
        "google-api-python-client==1.5.3",
        "google-cloud==0.21.0",
        "google-cloud-bigquery==0.22.1",
        "google-cloud-bigtable==0.22.0",
        "google-cloud-core==0.21.0",
        "google-cloud-datastore==0.22.1",
        "google-cloud-dns==0.22.0",
        "google-cloud-error-reporting==0.22.0",
        "google-cloud-happybase==0.22.0",
        "google-cloud-language==0.22.2",
        "google-cloud-logging==0.22.0",
        "google-cloud-monitoring==0.22.0",
        "google-cloud-pubsub==0.21.0",
        "google-cloud-resource-manager==0.22.0",
        "google-cloud-runtimeconfig==0.22.0",
        "google-cloud-storage==0.22.0",
        "google-cloud-translate==0.22.0",
        "google-cloud-vision==0.22.0",
        "google-gax==0.14.1",
        "googleapis-common-protos==1.5.0",
        "grpc-google-cloud-datastore-v1==0.14.0",
        "grpc-google-cloud-logging-v2==0.90.0",
        "grpc-google-iam-v1==0.10.1",
        "grpc-google-pubsub-v1==0.10.1",
        "grpcio==1.0.4",
        "gunicorn==19.4.5",
        "httplib2==0.9.2",
        "itsdangerous==0.24",
        "Jinja2==2.8.1",
        "lockfile==0.12.2",
        "luigi==2.2.0",
        "MarkupSafe==0.23",
        "marshmallow==2.10.5",
        "marshmallow-jsonapi==0.8.0",
        "mccabe==0.6.1",
        "mock==2.0.0",
        "MySQL-python==1.2.5",
        "oauth2client==3.0.0",
        "pbr==1.10.0",
        "ply==3.8",
        "protobuf==3.1.0.post1",
        "py==1.4.32",
        "py2neo==3.1.2",
        "pyasn1==0.1.9",
        "pyasn1-modules==0.0.8",
        "pycodestyle==2.3.1",
        "pyflakes==1.5.0",
        "PyMySQL==0.7.9",
        "pytest==2.9.2",
        "pytest-cov==2.3.0",
        "pytest-mock==1.1",
        "python-daemon==2.1.2",
        "python-dateutil==2.5.3",
        "requests==2.12.4",
        "rsa==3.4.2",
        "simplejson==3.10.0",
        "singledispatch==3.4.0.3",
        "six==1.10.0",
        "slacker==0.9.9",
        "SQLAlchemy==1.1.4",
        "sqlparse==0.2.1",
        "tablib==0.11.3",
        "tornado==4.4.2",
        "uritemplate==0.6",
        "visitor==0.1.3",
        "Werkzeug==0.11.15"
    ]
    # could also include long_description, download_url, classifiers, etc.
)
